/// <reference types="expo/types" />

// NOTE: This file is autogenerated by Expo — but we commit a minimal version
// so the typecheck passes before the first `expo prebuild`. The 3 slash
// directives above cover the ambient Expo router + config types.
